name: ServerRestartPE
main: iJoshuaHD\iMCPE\ASR\Loader
version: 3.0.0-B1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
author: VMPE Development Team
description: Restarts your server at given interval.
website: https://github.com/iJoshuaHD/ASR
commands:
 asr:
  description: "Set ASR Time"
  permission: asr.command.asr
 restart:
  description: "Check ASR Status"
  permission: asr.command.restart
permissions:
 asr.command.asr:
  description: "Usage: /asr <value>"
  default: op
 asr.command.restart:
  description: "Usage: /restart"
  default: true
